# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 290ef703d6a9c34070c1da31bf2c261c9a3f463e90fa99904bb6d56a191b05b5bff7e0007d3c12193ac19e3069b75b29327e84282b97cda4216b3a41c935e5a1

test:
  secret_key_base: 8fd404acdfb1ccaefbcd4136c6dd189e8cdbae15999f00212899a235fa86bc58a01a6248d52d4b2f615663319e5b4ac5fb441faa236dcc3ef84dc8cbfc219f6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
